[project]
name = "my-yolo-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ultralytics>=8.4.6",
    "opencv-python>=4.8.0.76",
]
